// Defining UI Actions
export const SHOW_SPINNER = "SHOW_SPINNER";
export const HIDE_SPINNER = "HIDE_SPINNER";

// Defining VendingMachine Actions
export const FETCH_VENDING_MACHINE_ITEMS = "FETCH_VENDING_MACHINE_ITEMS";
export const FETCH_VENDING_MACHINE_ITEMS_SUCCESS =
  "FETCH_VENDING_MACHINE_ITEMS_SUCCESS";
export const FETCH_VENDING_MACHINE_ITEMS_ERROR =
  "FETCH_VENDING_MACHINE_ITEMS_ERROR";
