// Defining UI Actions
export const SHOW_SPINNER = "SHOW_SPINNER";
export const HIDE_SPINNER = "HIDE_SPINNER";

// Defining VendingMachine Actions
export const FETCH_VENDING_MACHINE_ITEMS = "FETCH_VENDING_MACHINE_ITEMS";
export const FETCH_VENDING_MACHINE_ITEMS_SUCCESS =
  "FETCH_VENDING_MACHINE_ITEMS_SUCCESS";
export const FETCH_VENDING_MACHINE_ITEMS_ERROR =
  "FETCH_VENDING_MACHINE_ITEMS_ERROR";

// Defining Order Actions
export const FETCH_ORDERS = "FETCH_ORDERS";
export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";
export const FETCH_ORDERS_ERROR = "FETCH_ORDERS_ERROR";
export const ADD_NEW_ORDER = "ADD_NEW_ORDER";
export const ADD_NEW_ORDER_SUCCESS = "ADD_NEW_ORDER_SUCCESS";
export const ADD_NEW_ORDER_ERROR = "ADD_NEW_ORDER_ERROR";
export const ADD_ITEM_TO_ORDER_DETAIL = "ADD_ITEM_TO_ORDER_DETAIL";
export const DELIVER_ORDER = "DELIVER_ORDER";
export const DELIVER_ORDER_SUCCESS = "DELIVER_ORDER_SUCCESS";
export const DELIVER_ORDER_ERROR = "DELIVER_ORDER_ERROR";
